---
- name: buildind & pushing
  hosts: docker 
  tasks:
        - name: docker build
          shell: " docker build -t sayerameshbabu/dllms nodejs"
        - name: deleting container if exists
          shell: "docker stop lmscontainer"
          ignore_errors: yes
        - name: deleting container
          shell: "docker rm lmscontainer"
          ignore_errors: yes
        - name: creating container
          shell: "docker run -p 80:80 -dt --name lmscontainer sayerameshbabu/dllms"
        - name: push docker image
          shell: "docker push sayerameshbabu/dllms" 
...

